### PR TITLE
Solve atk4/data first - Remove old Travis files

### PR DESCRIPTION
**Pull request by mvorisek**
If needed anytime, they can be restored from history, but having old/ununsed files in repo is misleading.

### CODE REVIEW

**Comment by mvorisek** [comment]
Tests should be fixed once https://github.com/atk4/dsql/pull/179 is merged.

**Review by DarkSide666 — CHANGES_REQUESTED** [review]
I'm OK to remove `.old.travis.yml` file, but these phpunit config files was used not only by travis, but also you can use them when running tests locally (on localhost). So I would like to keep them as they are.

Also tests still fail.

**Comment by mvorisek** [comment]
> 
> 
> I'm OK to remove `.old.travis.yml` file, but these phpunit config files was used not only by travis, but also you can use them when running tests locally (on localhost). So I would like to keep them as they are.

So can we change the database hosts/configuratioon (should be possible) and use only one config file for local/GH?

I propose these changes as they are not self explanatory and it takes uneeded time get what is really does..

**Comment by mvorisek** [comment]
Closing in favor of PR #190

**Pull request closed without merging**
