### PR TITLE
Feature/fix cc issues 20160620

### LINKED ISSUE #81: Improve code climate
https://codeclimate.com/github/atk4/dsql/src/Query.php

Need to improve issues in this file.

### PR DESCRIPTION
**Pull request by DarkSide666**
fixes #81 

https://codeclimate.com/github/atk4/dsql/compare/feature/fix-cc-issues-20160620

### CODE REVIEW

**Comment by DarkSide666** [comment]
Method `_set_args` can also be written for not limited depth something like this:

```
/**
 * @param array $path Like ['table', $alias] or ['where', null]
 * @param mixed $value
 * @param bool $deny_overwrite
 */
    protected function _set_args($path, $value, $deny_overwrite = true)
    {
        $new_key = array_pop($path);
        
        // navigate
        $a = &$this->args;
        foreach ($path as $key) {
            if (!is_array($a)) {
                $a = array();
            }
            $a = &$a[$key];
        }

        // set value
        if ($new_key === null) {
            $a[] = $value;
        } else {
            if ($deny_overwrite && isset($a[$new_key])) {
                throw new Exception([
                    'Args element already set',
                    'path' => implode('/', $path)
                ]);
            }
            $a[$new_key] = $value;
        }
}
```

and used in all class methods, but I guess that will make performance worse because of additional method call.

**Comment by romaninsh** [comment]
Add documentation mention

**Comment by DarkSide666** [comment]
will do probably tonight

**Comment by romaninsh** [comment]
i think just mentioning this under internal method with some brief paragraph is enough.

**Comment by DarkSide666** [comment]
simple method description added in docs

**Pull request merged**
