### PR TITLE
Refactor driver type

### PR DESCRIPTION
**Pull request by mvorisek**

### CODE REVIEW

**Comment by DarkSide666** [comment]
What advantage it gives to just rename this property?
But overall I agree that `driverType` is more appropriate property name.

**Comment by mvorisek** [comment]
> 
> 
> What advantage it gives to just rename this property?
> But overall I agree that `driverType` is more appropriate property name.

`driver` is misleading, it it not an object representing driver. Once this is merged, we can refactor in other repos.

**Review by DarkSide666 — APPROVED** [review]
Added more changes required. Now looks good.

**Comment by mvorisek** [comment]
@DarkSide666 Perfect!

**Pull request merged**
