### PR TITLE
Run tests with bool column

### PR DESCRIPTION
**Pull request by mvorisek**

### CODE REVIEW

**Comment by DarkSide666** [comment]
Please no `bool` here because PgSQL will need to cast values to bool then and will fail tests. Casting for PgSQL is not implemented because treatment of datatypes in PgSQL is much more strict than in MySQL.

**Comment by mvorisek** [comment]
@DarkSide666 Experiment, maybe there is easy way to solve this. In this stage of course draft and DO NOT MERGE!

**Comment by mvorisek** [comment]
@DarkSide666 can you merge this https://github.com/atk4/data/pull/571 as promised "after a hour" days ago?

**Comment by DarkSide666** [comment]
yeah, sorry. had to work on projects too to earn some cash for living :)

**Comment by mvorisek** [comment]
@DarkSide666 make Atk big and you are safe! :D

**Comment by DarkSide666** [comment]
I doubt that toolkit as such (as framework) can be profitable.
Projects built on top of toolkit can.

**Review by DarkSide666 — APPROVED** [review]
Good way to fix this :)

**Pull request merged**
