### PR TITLE
[fix] destroy connection on test teardown

### PR DESCRIPTION
**Pull request by georgehristov**
Fix for Burn test "Too many connections" failure

### CODE REVIEW

**Review by DarkSide666 — APPROVED** [review]
LGTM.
Tests fail because new PHPUnit 9.5 doesn't have `getAnnotations()` method anymore.

**Review by mvorisek — CHANGES_REQUESTED** [review]
in Oracle, we have a special PDO reuse, maybe for this reason, try to remove it

if the tests pass then, then this is probably welcomed

also, what about the another test cases?

**Comment by georgehristov** [comment]
@mvorisek I saw tests failing (on MySQL) due to too many connections and I applied same fix as in data.
Just to describe it in words: the issue is that if a model is stored in test class property on test setUp then the connection is not closed on test tearDown unless this property is unset.
So each test creates one more connection until the connection limit is reached. If number of tests is below that limit then all appears fine.

**Comment by mvorisek** [comment]
I am not arguing it, see my additional commit about that Oracle issue. If these fixed by you solves it now here and in data, than both 👍

**Review by mvorisek — APPROVED** [review]

**Comment by mvorisek** [comment]
Oracle is not fixed by this... I think this fix is "correct" in sense of cleaness, ie. what is setup is released too.

**Pull request merged**
